config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
   
  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    ticker_symbol.upcase!
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1/'
    )
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_track?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end 

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_track?(ticker_symbol)
  end

  def full_name 
    if first_name || last_name
      return "#{first_name} #{last_name}" 
    else
      return "Anonymous"
    end
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friend_with?(friend_id)
    !self.friends.where(id: friend_id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name])
  end

  def after_sign_in_path_for(resource)
    my_portfolio_path # your path
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create 
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "Vous êtes désormais ami avec #{friend.first_name} #{friend.last_name}"
    else
      flash[:alert] = "Il y a une erreur lors du traitement de la requête"
    end
    redirect_to my_friends_path
  end

  def destroy 
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Relation bien supprimée"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController 

  def search 
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Ce nom d'action n'est pas valide"
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Veuillez saisir un nom d'action"
        format.js { render partial: 'users/result' }
      end
    end
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user:current_user, stock: stock)
    flash[:notice] = "L'action #{stock.name} à bien été ajouté à votre portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} à bien été supprimé"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def search
    if params[:name_friend].present?
      @friend = User.where(last_name: params[:name_friend]).first
      if @friend
        respond_to do |format|
          format.js { render partial: 'users/result_search_friend' }
        end
      else
        flash[:alert] = "Aucun utilisateur n'a été trouvé avec ce nom"
        respond_to do |format|
          format.js { render partial: 'users/result_search_friend' }
        end
      end
    else
      flash[:alert] = "Veuillez saisir un nom"
      respond_to do |format|
        format.js { render partial: 'users/result_search_friend' }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index 

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
<table class="table table-bordered table-hover mt-3">
  <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @friends.each do |friend| %>
    <tr>
      <td><%= friend.email %></td>
      <td><%= friend.first_name %></td>
      <td><%= friend.last_name %></td>
      <td><%= link_to "Stop following", friendships_path(friend), method: :delete, data: { confirm: "Etes vous sur de vouloir supprimer '#{friend.first_name} #{friend.last_name}' de vos amis' ?" },
              class: 'btn btn-small btn-warning' %><%= link_to 'View profile', user_path(friend), class: "btn btn-xs btn-success m-2" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/_messages.html.erb
<% if notice %>
<p class="notice alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Financetracker', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% portfolio_class_active = 'active' if request.path == my_portfolio_path %>
          <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link #{portfolio_class_active}" %>
        </li>
        <li class="nav-item">
          <% friends_class_active = 'active' if request.path == my_portfolio_path %>
          <%= link_to "My friends", my_friends_path, class: "nav-link #{friends_class_active}" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mx-2 user-name">
          <%= current_user.full_name if current_user %>
        </li>
        <li class="nav-item mx-2">
          <%= link_to("Logout", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :delete ) if current_user %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<table class="table table-bordered table-hover mt-3">
  <thead>
    <tr>
      <th scope="col">Ticker</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @tracked_stocks.each do |stock| %>
    <tr>
      <td><%= stock.ticker %></td>
      <td><%= stock.name %></td>
      <td><%= stock.last_price %></td>
      <td>
      <% if current_user.id == @user.id %>
      <%= link_to "Remove", user_stock_path(stock), method: :delete, data: { confirm: "Etes vous sur de vouloir supprimer l'action '#{stock.ticker}' ?" },
              class: 'btn btn-small btn-warning' %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/_result.html.erb
<div class="results-block">
    <%= render 'layouts/messages' %>
</div>

<% if @stock %>
<div class="card card-header results-block">
    <strong>Symbol: </strong><%= @stock.ticker %>
    <strong>Name: </strong><%= @stock.name %>
    <strong>Price: </strong><%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
    <%=  link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                                    class: "btn btn-xs btn-success", method: :post %>
    <% elsif !current_user.under_stock_limit? %>
        <span class="badge bg-secondary">Vous trackez déja 10 actions</span>
    <% elsif current_user.stock_already_track?(@stock.ticker) %>
        <span class="badge bg-secondary">Vous trackez déja cette action</span>
    <% end %>
</div>
<% end %>

app/views/users/_result.js.erb
document.querySelector("#results").innerHTML = "<%= j render 'users/result.html' %>"

app/views/users/_result_search_friend.html.erb
<div class="results-block">
    <%= render 'layouts/messages' %>
</div>

<% if @friend %>
<div class="card card-header results-block">
    <strong>Prénom: </strong><%= @friend.first_name %>
    <strong>Nom: </strong><%= @friend.last_name %>
    <% if current_user.not_friend_with?(@friend.id) %>
    <%= link_to 'Follow user', friendships_path(friend: @friend), class: "btn btn-xs btn-success", method: :post %>
    <% else %>
    <span class="badge bg-secondary">Vous êtes amis</span>
    <% end %>
    <%= link_to 'View profile', user_path(friend), class: "btn btn-xs btn-success" %>
</div>
<% end %>

app/views/users/_result_search_friend.js.erb
document.querySelector("#results").innerHTML = "<%= j render 'users/result_search_friend.html' %>"

app/views/users/my_friends.html.erb
<h1>My portfolio</h1>
<div class="search-area">
    <h3>Search friends</h3>
    <%= form_tag search_friend_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :name_friend, params[:name_friend], placeholder: "Nom de votre ami", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= "Search" %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>
<div id="results">

</div>
<% if !@friends.empty? %>
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>
<div class="search-area">
    <h3>Search stocks</h3>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :stock, params[:stock], placeholder: "Référence de l'action", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= "Search" %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>
<div id="results">

</div>
<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<% if @user %>
<div class="card card-header results-block">
    <p>Profil de <%= @user.first_name %> <%= @user.last_name %></p>
    <% if current_user.not_friend_with?(@user.id) %>
    <%= link_to 'Follow user', friendships_path(friend: @user), class: "btn btn-xs btn-success", method: :post %>
    <% else %>
    <span class="badge bg-secondary">Vous êtes amis</span>
    <% end %>
</div>

<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% else %>
    <p class="no-stocks-user">Cet utilisateur ne traque aucune action</p>
<% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Bienvenue sur notre application de tracking de stocks</h1>

<%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %>